name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Thanks for opening your first issue! We’ll look into it soon 🚀"
        pr-message: "🎉 Thanks for your first pull request! One of our team members will review it shortly."

